# Generated by Django 3.0.5 on 2020-04-08 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(max_length=255)),
                ('book_avail', models.CharField(max_length=255)),
                ('book_publish', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_version', models.FloatField()),
                ('book_price', models.PositiveIntegerField()),
                ('publish_year', models.DateTimeField(default=datetime.datetime(2020, 4, 8, 15, 28, 21, 144278, tzinfo=utc))),
                ('booktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.booktype')),
            ],
        ),
    ]
