# Generated by Django 3.0.5 on 2020-04-09 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20200409_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='publish_year',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 8, 10, 31, 223275, tzinfo=utc)),
        ),
    ]
