# Generated by Django 3.0.5 on 2020-04-09 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_auto_20200409_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_version',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='booktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.booktype'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publish_year',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 8, 12, 15, 143019, tzinfo=utc), null=True),
        ),
    ]
